### ISSUE TITLE
Is This The Latest Source?

### ISSUE THREAD

**Issue by xioustic** [Evilnames/PomoTracker#1]
Hey, it's Christian. Did you ever get any farther on this? The source-code on here seems wildly outdated compared to how far you got at the meetup.

Did some brief reading on the Pomodoro method so was somewhat looking forward to watching this pan out and possibly helping out.

**Comment by Evilnames** [comment]
I'll push the latest version up this week.  I didn't have time to work on it this weekend :(

**Comment by xioustic** [comment]
Sweet, thanks man. Maybe I'll find some free time to help out between my certs. Will help flesh out my github at least. And the final result might help keep me from tunnel visioning my day away.
